name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs checks on PRs to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_DATA_PATH: src/data/portfolio-data.json
      VITE_PUBLIC_DATA_URL: ${{ secrets.VITE_PUBLIC_DATA_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Create .env file from GitHub secrets
      - name: Create environment file
        run: |
          echo "VITE_DATA_PATH=$VITE_DATA_PATH" >> .env
          echo "VITE_PUBLIC_DATA_URL=$VITE_PUBLIC_DATA_URL" >> .env
        
      - name: Create data directory
        run: mkdir -p dist/src/data

      - name: Copy portfolio data
        run: cp src/data/portfolio-data.json dist/src/data/

      - name: Build project
        run: npm run build

      # Upload JSON to CDN only if the secret exists
      - name: Check if CDN upload URL exists
        id: check_cdn
        run: |
          if [ -n "${{ secrets.CDN_UPLOAD_URL }}" ]; then
            echo "::set-output name=has_url::true"
          else
            echo "::set-output name=has_url::false"
          fi

      - name: Upload portfolio data to CDN
        if: steps.check_cdn.outputs.has_url == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d @src/data/portfolio-data.json \
          ${{ secrets.CDN_UPLOAD_URL }}
        continue-on-error: true

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod --env VITE_DATA_PATH=${{ env.VITE_DATA_PATH }} --env VITE_PUBLIC_DATA_URL=${{ env.VITE_PUBLIC_DATA_URL }}'
