name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs checks on PRs to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # You can match your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Optionally, run tests (if you have any)
      # - name: Run tests
      #   run: npm test

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./  # adjust if your project is in a subfolder
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
